export const ORDER_CREATE_REQUEST = 'ORDER_CREATED_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATED_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATED_FAIL'
export const ORDER_CREATE_RESET = 'ORDER_CREATED_RESET'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'